languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
baseurl = "/"
googleAnalytics = ""
theme = "hugo-vitae"

[params]
  author = "Dwai Banerjee"
  title = "Dwai Banerjee's Resume"
  description = "Dwai Banerjee's Awesome Resume"
  avatar = "3b27979.jpg"
  email = "dbanerj@gmail.com"
  email_full = "mailto:dbanerj@gmail.com"
  website = "cloudgear.io"
  website_full = "http://www.cloudgear.io"
  github = "dwaiba"
  twitter = "cloudgeario"
  #tel = "+44 0000 000000"
  #tel_full = "+440000000000"
  google_maps = "https://www.google.com/maps/place/Woudlaan+Zoetermeer"
  #address = "44 Perth Street"
  #postcode = "EH3 5BL"
  city = "Zoetermeer"
  country = "The Netherlands"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
